pipeline {
   agent any
   stages {
      stage('构建') {
         steps {
            echo 'Hello World'
         }
      }
      stage('审查') {
         steps {
            sleep 5
            echo 'test...'
         }
      }
      stage('DevOps') {
         steps {
            echo 'end DevOps....'
         }
      }
   }
}
